spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    database-platform: "org.hibernate.dialect.H2Dialect"
    url: "jdbc:h2:mem:src-ms-portability"
    username: "sa"
    password: ""
  h2:
    console:
      enabled: "true"
      settings:
        web-allow-others: "true"
        trace: "true"
      path: "/h2-console"
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.apache.kafka.common.serialization.StringSerializer
topic:
  name:
    producer: ocpv08td-src-ms-portability-create
